language: ruby
rvm:
- 2.3.3
install:
- bundle install
before_script:
   - chmod +x ./script/cibuild 

script:  
  - ./script/cibuild
  -  bash ./deploy.sh
branches:
  only:
  - master
env:
  - secure: hz+8tdcnI+1elxD7e2dQTRYqdka7h/ZVkx9ta0LLzByx2Tthd+6RukiO3W2HPwwJWwwin78Mfggfxo8rHCyL9dwheGDpH5JMqsu8uEpGVzhPiYk3dUQMIVMOrGpKWbtqpnfULeF877XEiLGntZgNqGtdLDOH+RsnfO+tdgIlZb3Xokguuq/qRyVCoO+dOrnV+RdfkL7HK/ETWqPvm3LT3R6bTlTVvSwVHUyiSRqQmNMPHXT152SNpSJT9I8T4Dp1JrIfzffNAnnW43NBDYOZPC/qq+r3cphBK7DhG0vktfSdFtNeBZCDNu0LHwc/FeNp+8K+S0YR0Ju2re7PmkDH83kA8n8O2V4I8ibe3fjzgDtA/1tn6XoJnDpjzrLjLN8OInDELv20Q8BSILZtTQQP5fwbvd1QAcMAJkUXozUkoqKl9w+rzjr1F7qXx+DlEfulQoF4EXv6q/zXUrH/boPY8cCupn1BqoXkwmm8KMJn7ZNO83wUMVOxyeT2svCGzSO/RuH0oXN7hXIdL0V1T/1pxFPLjfnH9WqzoB/O3RfvZ9eCvFL2TxOKSh31NYf6SCbjnUN90pTwodIb/iglzpiNkg1Dns/ewJQC7tRWH+jvNJI1cpFB8wxsP3fC29QW2Y+PVpz817M37Ps03U++uWr3O9CPNdpvK8iNpnfaXPO2/WY=
exclude:
- vendor
sudo: false
 