# Permalinks
permalink:           pretty

# Setup
title:               Bradford Condon PhD
tagline:             Genomics, Bioinformatics, Mobile and Web Development
url:                 http://bradfordcondon.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bradford Confon
  email:             bradford.condon@uky.edu


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
