# Permalinks
permalink:           pretty

# Setup
title:               Bradford Condon PhD
tagline:             Bioinformatics, Web & Mobile Development
url:                 http://bradfordcondon.com
paginate:            5
baseurl:             ""
description:        I am a bioinformaticist and mobile/web developer living in Lexington, KY.

# Assets
#
# We specify the directory for Jekyll so we can use @imports.

# About/contact
author:
  name:              Bradford Confon
  email:             bradford.condon@uky.edu


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
